name = "NeuralOcenanigans"
uuid = "23a5ca72-87e4-4a94-a405-cc4477d5c591"
authors = ["Andriy Drozdyuk <andriy@drozdyuk.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
